import subprocess
import time
import concurrent.futures

tech_suffixes = [
    # Need to generate more meaningful tech/brand suffixes!
    ("hq", "Headquarters", "ہیڈ کوارٹر / مرکز"),
    ("os", "Operating System", "آپریٹنگ سسٹم"),
    ("ai", "Artificial Intelligence", "مصنوعی ذہانت"),
    ("ui", "User Interface", "یوزر انٹرفیس"),
    ("ux", "User Experience", "یوزر ایکسپیرینس"),
    ("io", "Input/Output", "ان پٹ آؤٹ پٹ"),
    ("co", "Company", "کمپنی"),
    ("go", "Go/Action", "آگے بڑھنا"),
    ("up", "Up/Growth", "اوپر / ترقی"),
    ("do", "Do/Action", "کام کرنا"),
    ("on", "On/Active", "ایکٹو / آن"),
    ("in", "In/Inside", "اندر / شامل"),
    ("now", "Now/Instant", "ابھی / فوراً"),
    ("run", "Run/Execute", "چلانا"),
    ("fly", "Fly/Speed", "اڑنا / تیزی"),
    ("try", "Try/Test", "کوشش کرنا"),
    ("get", "Get/Acquire", "حاصل کرنا"),
    ("set", "Set/Ready", "تیار کرنا"),
    ("put", "Put/Place", "رکھنا"),
    ("add", "Add/Plus", "شامل کرنا"),
    ("win", "Win/Success", "جیت / کامیابی"),
    ("top", "Top/Peak", "چوٹی / ٹاپ"),
    ("key", "Key/Core", "چابی / اہم"),
    ("way", "Way/Path", "راستہ"),
    ("fix", "Fix/Repair", "درست کرنا"),
    ("mix", "Mix/Blend", "ملانا"),
    ("tag", "Tag/Label", "ٹیگ"),
    ("map", "Map/Navigate", "نقشہ"),
    ("nav", "Navigate", "راستہ دکھانا"),
    ("log", "Log/Record", "ریکارڈ / لاگ"),
    ("bot", "Bot/Robot", "روبوٹ"),
    ("api", "API", "اے پی آئی"),
    ("app", "App/Application", "ایپلیکیشن"),
    ("dev", "Developer", "ڈیویلپر"),
    ("sec", "Security", "سیکیورٹی"),
    ("doc", "Document", "دستاویز"),
    ("env", "Environment", "ماحول"),
    ("git", "Git/Code", "گٹ / کوڈ"),
    ("web", "Web/Internet", "ویب"),
    ("net", "Net/Network", "نیٹ ورک"),
    ("org", "Organization", "تنظیم"),
    ("biz", "Business", "کاروبار"),
    ("seo", "SEO", "ایس ای او"),
    ("ad", "Ad/Advertising", "اشتہار"),
    ("pay", "Pay/Payment", "ادائیگی"),
    ("buy", "Buy/Shop", "خریدنا"),
    ("cart", "Cart/Shop", "کارٹ"),
    ("shop", "Shop/Store", "دکان"),
    ("mall", "Mall/Market", "شاپنگ مال"),
    ("mart", "Mart/Market", "مارٹ"),
    ("deal", "Deal/Offer", "ڈیل / آفر"),
    ("sale", "Sale/Discount", "سیل"),
    ("bid", "Bid/Auction", "بولی"),
    ("host", "Host/Server", "ہوسٹ"),
    ("cloud", "Cloud", "کلاؤڈ"),
    ("node", "Node/Server", "نوڈ"),
    ("port", "Port/Gateway", "پورٹ"),
    ("ping", "Ping/Network", "پنگ"),
    ("sync", "Sync", "ہم آہنگی"),
    ("link", "Link", "رابطہ"),
    ("push", "Push/Deploy", "پش / بھیجنا"),
    ("pull", "Pull/Retrieve", "پل / لانا"),
    ("cast", "Cast/Broadcast", "نشر کرنا"),
    ("play", "Play/Media", "پلے / چلانا"),
    ("show", "Show/Display", "دکھانا"),
    ("view", "View", "دیکھنا"),
    ("look", "Look", "دیکھنا"),
    ("find", "Find/Search", "تلاش کرنا"),
    ("seek", "Seek", "تلاش کرنا"),
    ("meet", "Meet", "ملنا"),
    ("join", "Join", "شامل ہونا"),
    ("chat", "Chat/Talk", "بات چیت"),
    ("talk", "Talk", "بات کرنا"),
    ("call", "Call", "کال کرنا"),
    ("dial", "Dial", "ڈائل کرنا"),
    ("mail", "Mail/Email", "میل"),
    ("post", "Post/Mail", "پوسٹ"),
    ("send", "Send", "بھیجنا"),
    ("drop", "Drop", "گرانا / ڈراپ"),
    ("lift", "Lift", "اٹھانا"),
    ("rise", "Rise", "بڑھنا / عروج"),
    ("soar", "Soar", "اڑان بھرنا"),
    ("peak", "Peak", "چوٹی"),
    ("zen", "Zen/Calm", "پرسکون"),
    ("aura", "Aura/Vibe", "احساس / اورا"),
    ("vibe", "Vibe/Energy", "احساس / وائب"),
    ("soul", "Soul/Core", "روح"),
    ("mind", "Mind/Intellect", "ذہن"),
    ("brain", "Brain", "دماغ"),
    ("idea", "Idea", "آئیڈیا / سوچ"),
    ("plan", "Plan", "منصوبہ"),
    ("goal", "Goal", "مقصد"),
    ("step", "Step", "قدم"),
    ("leap", "Leap", "چھلانگ"),
    ("jump", "Jump", "چھلانگ"),
    ("dash", "Dash", "تیزی"),
    ("rush", "Rush", "بھاگنا"),
    ("fast", "Fast", "تیز"),
    ("quick", "Quick", "جلدی"),
    ("swift", "Swift", "تیز رفتار"),
    ("rapid", "Rapid", "تیز"),
    ("speed", "Speed", "رفتار"),
    ("pace", "Pace", "رفتار"),
    ("flow", "Flow", "بہاؤ"),
    ("wave", "Wave", "لہر"),
    ("tide", "Tide", "لہر"),
    ("surf", "Surf", "سرف کرنا"),
    ("sail", "Sail", "سمندری سفر"),
    ("boat", "Boat", "کشتی"),
    ("ship", "Ship", "بحری جہاز"),
    ("crew", "Crew", "عملہ"),
    ("team", "Team", "ٹیم"),
    ("gang", "Gang", "گروہ"),
    ("club", "Club", "کلب"),
    ("base", "Base", "بنیاد"),
    ("camp", "Camp", "کیمپ"),
    ("site", "Site", "جگہ / سائٹ"),
    ("spot", "Spot", "مقام"),
    ("place", "Place", "جگہ"),
    ("space", "Space", "خلا / جگہ"),
    ("room", "Room", "کمرہ"),
    ("hall", "Hall", "ہال"),
    ("deck", "Deck", "ڈیک"),
    ("floor", "Floor", "فرش"),
    ("level", "Level", "سطح"),
    ("stage", "Stage", "سٹیج"),
    ("phase", "Phase", "مرحلہ"),
    ("part", "Part", "حصہ"),
    ("piece", "Piece", "ٹکڑا"),
    ("bit", "Bit", "تھوڑا / بٹ"),
    ("dot", "Dot", "نقطہ"),
    ("mark", "Mark", "نشان"),
    ("sign", "Sign", "علامت"),
    ("logo", "Logo", "لوگو"),
    ("icon", "Icon", "آئیکن"),
    ("brand", "Brand", "برانڈ"),
    ("name", "Name", "نام"),
    ("word", "Word", "لفظ"),
    ("text", "Text", "متن"),
    ("type", "Type", "ٹائپ / قسم"),
    ("font", "Font", "فانٹ"),
    ("color", "Color", "رنگ"),
    ("hue", "Hue", "رنگت"),
    ("tint", "Tint", "رنگ"),
    ("shade", "Shadow/Shade", "سایہ"),
    ("glow", "Glow", "چمک"),
    ("shine", "Shine", "چمکنا"),
    ("light", "Light", "روشنی"),
    ("dark", "Dark", "اندھیرا"),
    ("dim", "Dim", "مدھم"),
    ("fade", "Fade", "مدھم ہونا"),
    ("blur", "Blur", "دھندلا"),
    ("clear", "Clear", "صاف"),
    ("pure", "Pure", "خالص"),
    ("true", "True", "سچ"),
    ("real", "Real", "حقیقی"),
    ("good", "Good", "اچھا"),
    ("best", "Best", "بہترین"),
    ("fine", "Fine", "عمدہ"),
    ("nice", "Nice", "اچھا"),
    ("cool", "Cool", "شاندار"),
    ("rad", "Rad/Cool", "زبردست"),
    ("epic", "Epic", "عظیم"),
    ("grand", "Grand", "شاندار"),
    ("mega", "Mega", "بہت بڑا"),
    ("ultra", "Ultra", "الٹرا / حد سے زیادہ"),
    ("hyper", "Hyper", "انتہائی"),
    ("super", "Super", "سپر"),
    ("pro", "Pro", "پرو"),
    ("max", "Max", "میکس"),
    ("plus", "Plus", "پلس"),
    ("extra", "Extra", "اضافی"),
    ("more", "More", "مزید"),
    ("less", "Less", "کم"),
    ("few", "Few", "چند"),
    ("some", "Some", "کچھ"),
    ("many", "Many", "بہت"),
    ("much", "Much", "زیادہ"),
    ("all", "All", "سب"),
    ("every", "Every", "ہر ایک"),
    ("any", "Any", "کوئی بھی"),
    ("one", "One", "ایک"),
    ("two", "Two", "دو"),
    ("dual", "Dual", "دہرا"),
    ("twin", "Twin", "جڑواں"),
    ("pair", "Pair", "جوڑا"),
    ("duo", "Duo", "دو"),
    ("trio", "Trio", "تین"),
    ("quad", "Quad", "چار"),
    ("poly", "Poly", "کئی"),
    ("multi", "Multi", "متعدد"),
    ("omni", "Omni", "ہر جگہ"),
    ("pan", "Pan", "سب"),
    ("uni", "Uni", "ایک"),
    ("mono", "Mono", "اکیلا"),
    ("solo", "Solo", "تنہا"),
    ("lone", "Lone", "تنہا"),
    ("only", "Only", "صرف"),
    ("just", "Just", "صرف / انصاف"),
    ("fair", "Fair", "منصفانہ"),
    ("even", "Even", "برابر"),
    ("odd", "Odd", "طاق"),
    ("new", "New", "نیا"),
    ("fresh", "Fresh", "تازہ"),
    ("raw", "Raw", "خام"),
    ("rare", "Rare", "نایاب"),
    ("old", "Old", "پرانا"),
    ("past", "Past", "ماضی"),
    ("late", "Late", "دیر"),
    ("early", "Early", "جلدی"),
    ("soon", "Soon", "جلد"),
    ("next", "Next", "اگلا"),
    ("then", "Then", "پھر"),
    ("now", "Now", "اب"),
    ("here", "Here", "یہاں"),
    ("there", "There", "وہاں"),
    ("near", "Near", "قریب"),
    ("far", "Far", "دور"),
    ("away", "Away", "دور"),
    ("out", "Out", "باہر"),
    ("in", "In", "اندر"),
    ("up", "Up", "اوپر"),
    ("down", "Down", "نیچے"),
    ("over", "Over", "اوپر"),
    ("under", "Under", "نیچے"),
    ("high", "High", "اونچا"),
    ("low", "Low", "نیچا"),
    ("tall", "Tall", "لمبا"),
    ("short", "Short", "چھوٹا"),
    ("long", "Long", "طویل"),
    ("wide", "Wide", "چوڑا"),
    ("broad", "Broad", "وسیع"),
    ("deep", "Deep", "گہرا"),
    ("flat", "Flat", "ہموار"),
    ("round", "Round", "گول"),
    ("square", "Square", "مربع"),
    ("cube", "Cube", "مربع نما"),
    ("block", "Block", "بلاک"),
    ("brick", "Brick", "اینٹ"),
    ("stone", "Stone", "پتھر"),
    ("rock", "Rock", "چٹان"),
    ("sand", "Sand", "ریت"),
    ("dust", "Dust", "گرد"),
    ("dirt", "Dirt", "مٹی"),
    ("clay", "Clay", "مٹی"),
    ("mud", "Mud", "کیچڑ"),
    ("soil", "Soil", "مٹی"),
    ("land", "Land", "زمین"),
    ("earth", "Earth", "زمین"),
    ("world", "World", "دنیا"),
    ("globe", "Globe", "گلوب"),
    ("star", "Star", "ستارہ"),
    ("moon", "Moon", "چاند"),
    ("sun", "Sun", "سورج"),
    ("sky", "Sky", "آسمان"),
    ("cloud", "Cloud", "بادل"),
    ("rain", "Rain", "بارش"),
    ("snow", "Snow", "برف"),
    ("ice", "Ice", "برف"),
    ("wind", "Wind", "ہوا"),
    ("air", "Air", "ہوا"),
    ("fire", "Fire", "آگ"),
    ("heat", "Heat", "گرمی"),
    ("cold", "Cold", "سردی"),
    ("warm", "Warm", "گرم"),
    ("hot", "Hot", "گرم"),
    ("cool", "Cool", "ٹھنڈا"),
    ("chill", "Chill", "ٹھنڈا"),
    ("freeze", "Freeze", "جما ہوا"),
    ("melt", "Melt", "پگھلنا"),
    ("burn", "Burn", "جلنا"),
    ("glow", "Glow", "چمک"),
    ("spark", "Spark", "چنگاری"),
    ("flash", "Flash", "چمک"),
    ("ray", "Ray", "کرن"),
    ("beam", "Beam", "شعاع"),
    ("line", "Line", "لکیر"),
    ("rule", "Rule", "اصول"),
    ("law", "Law", "قانون"),
    ("code", "Code", "ضابطہ"),
    ("norm", "Norm", "معیار"),
    ("form", "Form", "شکل"),
    ("shape", "Shape", "شکل"),
    ("size", "Size", "حجم"),
    ("mass", "Mass", "کمیت"),
    ("bulk", "Bulk", "تھوک"),
    ("weight", "Weight", "وزن"),
    ("heavy", "Heavy", "بھاری"),
    ("light", "Light", "ہلکا"),
    ("soft", "Soft", "نرم"),
    ("hard", "Hard", "سخت"),
    ("firm", "Firm", "مضبوط"),
    ("solid", "Solid", "ٹھوس"),
    ("fluid", "Fluid", "سیال"),
    ("liquid", "Liquid", "مائع"),
    ("gas", "Gas", "گیس"),
    ("vapor", "Vapor", "بھاپ"),
    ("steam", "Steam", "بھاپ"),
    ("smoke", "Smoke", "دھواں"),
    ("fog", "Fog", "دھند"),
    ("mist", "Mist", "دھند"),
    ("haze", "Haze", "دھندلاپن"),
    ("smog", "Smog", "سموگ"),
    ("dust", "Dust", "گرد"),
    ("ash", "Ash", "راکھ"),
    ("coal", "Coal", "کوئلہ"),
    ("wood", "Wood", "لکڑی"),
    ("tree", "Tree", "درخت"),
    ("leaf", "Leaf", "پتہ"),
    ("root", "Root", "جڑ"),
    ("stem", "Stem", "تنا"),
    ("branch", "Branch", "شاخ"),
    ("seed", "Seed", "بیج"),
    ("nut", "Nut", "گری دار میوہ"),
    ("fruit", "Fruit", "پھل"),
    ("flower", "Flower", "پھول"),
    ("bloom", "Bloom", "کھلنا"),
    ("bud", "Bud", "کلی"),
    ("plant", "Plant", "پودا"),
    ("grass", "Grass", "گھاس"),
    ("weed", "Weed", "جڑی بوٹی"),
    ("moss", "Moss", "کائی"),
    ("fern", "Fern", "فرن"),
    ("bush", "Bush", "جھاڑی"),
    ("shrub", "Shrub", "جھاڑی"),
    ("vine", "Vine", "بیل"),
    ("crop", "Crop", "فصل"),
    ("farm", "Farm", "کھیت"),
    ("field", "Field", "میدان"),
    ("yard", "Yard", "صحن"),
    ("lawn", "Lawn", "لان"),
    ("park", "Park", "پارک"),
    ("garden", "Garden", "باغ"),
    ("forest", "Forest", "جنگل"),
    ("wood", "Wood", "جنگل / لکڑی"),
    ("grove", "Grove", "درختوں کا جھنڈ"),
    ("orchard", "Orchard", "باغ"),
    ("vine", "Vineyard", "انگور کا باغ"),
    ("desert", "Desert", "صحرا"),
    ("plain", "Plain", "میدان"),
    ("valley", "Valley", "وادی"),
    ("hill", "Hill", "پہاڑی"),
    ("mount", "Mountain", "پہاڑ"),
    ("ridge", "Ridge", "پہاڑی سلسلہ"),
    ("cliff", "Cliff", "چٹان"),
    ("rock", "Rock", "چٹان"),
    ("stone", "Stone", "پتھر"),
    ("cave", "Cave", "غار"),
    ("hole", "Hole", "سوراخ"),
    ("pit", "Pit", "گڑھا"),
    ("ditch", "Ditch", "کھائی"),
    ("trench", "Trench", "خندق"),
    ("canal", "Canal", "نہر"),
    ("river", "River", "دریا"),
    ("stream", "Stream", "ندیا"),
    ("creek", "Creek", "چشمہ"),
    ("brook", "Brook", "ندی"),
    ("pool", "Pool", "تالااب"),
    ("pond", "Pool", "تالااب"),
    ("lake", "Lake", "جھیل"),
    ("sea", "Sea", "سمندر"),
    ("ocean", "Ocean", "بحر"),
    ("gulf", "Gulf", "خلیج"),
    ("bay", "Bay", "خلیج"),
    ("cove", "Cove", "چھوٹی خلیج"),
    ("port", "Port", "بندرگاہ"),
    ("dock", "Dock", "ڈاک"),
    ("pier", "Pier", "گھاٹ"),
    ("wharf", "Wharf", "گھاٹ"),
    ("quay", "Quay", "گھاٹ"),
    ("bank", "Bank", "کنارہ"),
    ("shore", "Shore", "ساحل"),
    ("coast", "Coast", "ساحل"),
    ("beach", "Beach", "ساحل سمندر"),
    ("sand", "Sand", "ریت"),
    ("dune", "Dune", "ریت کا ٹیلا"),
    ("reef", "Reef", "چٹان"),
    ("isle", "Isle", "جزیرہ"),
    ("island", "Island", "جزیرہ"),
    ("cape", "Cape", "راس"),
    ("point", "Point", "نقطہ"),
    ("head", "Head", "سر"),
    ("tail", "Tail", "دم"),
    ("back", "Back", "پیچھے"),
    ("front", "Front", "سامنے"),
    ("side", "Side", "پہلو"),
    ("edge", "Edge", "کنارہ"),
    ("rim", "Rim", "کنارہ"),
    ("brim", "Brim", "کنارہ"),
    ("lip", "Lip", "ہونٹ"),
    ("mouth", "Mouth", "منہ"),
    ("nose", "Nose", "ناک"),
    ("eye", "Eye", "آنکھ"),
    ("ear", "Ear", "کان"),
    ("hair", "Hair", "بال"),
    ("skin", "Skin", "جلد"),
    ("bone", "Bone", "ہڈی"),
    ("flesh", "Flesh", "گوشت"),
    ("blood", "Blood", "خون"),
    ("vein", "Vein", "رگ"),
    ("nerve", "Nerve", "اعصاب"),
    ("cell", "Cell", "خلیہ"),
    ("core", "Core", "مرکز"),
    ("heart", "Heart", "دل"),
    ("mind", "Mind", "ذہن"),
    ("soul", "Soul", "روح"),
    ("spirit", "Spirit", "روح"),
    ("ghost", "Ghost", "بھوت"),
    ("demon", "Demon", "بدروح"),
    ("angel", "Angel", "فرشتہ"),
    ("god", "God", "خدا"),
    ("lord", "Lord", "آقا"),
    ("king", "King", "بادشاہ"),
    ("queen", "Queen", "ملکہ"),
    ("prince", "Prince", "شہزادہ"),
    ("knight", "Knight", "نائٹ"),
    ("hero", "Hero", "ہیرو"),
    ("star", "Star", "ستارہ"),
    ("idol", "Idol", "آئیڈیل"),
    ("icon", "Icon", "آئیکن"),
    ("boss", "Boss", "باس"),
    ("chief", "Chief", "سربراہ"),
    ("head", "Head", "سربراہ"),
    ("lead", "Lead", "قیادت"),
    ("guide", "Guide", "رہنما"),
    ("coach", "Coach", "کوچ"),
    ("mentor", "Mentor", "استاد"),
    ("tutor", "Tutor", "استاد"),
    ("teacher", "Teacher", "معلم"),
    ("master", "Master", "ماسٹر"),
    ("guru", "Guru", "گرو"),
    ("sage", "Sage", "دانا"),
    ("wise", "Wise", "عقلمند"),
    ("smart", "Smart", "ہوشیار"),
    ("clever", "Clever", "چالاک"),
    ("sharp", "Sharp", "تیز"),
    ("keen", "Keen", "شوقین"),
    ("eager", "Eager", "مشتاق"),
    ("ready", "Ready", "تیار"),
    ("set", "Set", "تیار"),
    ("fit", "Fit", "فٹ"),
    ("well", "Well", "ٹھیک"),
    ("good", "Good", "اچھا"),
    ("fine", "Fine", "عمدہ"),
    ("okay", "Okay", "ٹھیک"),
    ("sure", "Sure", "یقینی"),
    ("true", "True", "سچ"),
    ("real", "Real", "حقیقی"),
    ("exact", "Exact", "درست"),
    ("right", "Right", "صحیح"),
    ("left", "Left", "بائیں"),
    ("up", "Up", "اوپر"),
    ("down", "Down", "نیچے"),
    ("in", "In", "اندر"),
    ("out", "Out", "باہر"),
    ("on", "On", "آن"),
    ("off", "Off", "آف"),
    ("yes", "Yes", "ہاں"),
    ("no", "No", "نہیں"),
    ("maybe", "Maybe", "شاید"),
    ("some", "Some", "کچھ"),
    ("any", "Any", "کوئی بھی"),
    ("all", "All", "سب"),
    ("none", "None", "کوئی نہیں"),
    ("each", "Each", "ہر ایک"),
    ("every", "Every", "ہر ایک"),
    ("both", "Both", "دونوں"),
    ("few", "Few", "چند"),
    ("many", "Many", "بہت"),
    ("much", "Much", "زیادہ"),
    ("more", "More", "مزید"),
    ("most", "Most", "زیادہ تر"),
    ("less", "Less", "کم"),
    ("least", "Least", "سب سے کم"),
    ("very", "Very", "بہت"),
    ("too", "Too", "بہت"),
    ("so", "So", "تو"),
    ("such", "Such", "ایسا"),
    ("just", "Just", "بس"),
    ("only", "Only", "صرف"),
    ("even", "Even", "یہاں تک کہ"),
    ("also", "Also", "بھی"),
    ("too", "Too", "بھی"),
    ("yet", "Yet", "ابھی تک"),
    ("still", "Still", "ابھی تک"),
    ("now", "Now", "اب"),
    ("then", "Then", "پھر"),
    ("once", "Once", "ایک بار"),
    ("twice", "Twice", "دو بار"),
    ("first", "First", "پہلا"),
    ("last", "Last", "آخری"),
    ("next", "Next", "اگلا"),
    ("past", "Past", "ماضی"),
    ("future", "Future", "مستقبل"),
    ("time", "Time", "وقت"),
    ("date", "Date", "تاریخ"),
    ("day", "Day", "دن"),
    ("night", "Night", "رات"),
    ("week", "Week", "ہفتہ"),
    ("month", "Month", "مہینہ"),
    ("year", "Year", "سال"),
    ("era", "Era", "دور"),
    ("age", "Age", "عمر / دور"),
    ("epoch", "Epoch", "عہد"),
    ("eon", "Eon", "عہد"),
    ("period", "Period", "مدت"),
    ("span", "Span", "عرصہ"),
    ("spell", "Spell", "مدت"),
    ("term", "Term", "مدت"),
    ("while", "While", "جبکہ"),
    ("moment", "Moment", "لمحہ"),
    ("minute", "Minute", "منٹ"),
    ("hour", "Hour", "گھنٹہ"),
    ("clock", "Clock", "گھڑی"),
    ("watch", "Watch", "دیکھنا / گھڑی"),
    ("dial", "Dial", "ڈائل"),
    ("face", "Face", "چہرہ"),
    ("hand", "Hand", "ہاتھ"),
    ("arm", "Arm", "بازو"),
    ("leg", "Leg", "ٹانگ"),
    ("foot", "Foot", "پاؤں"),
    ("toe", "Toe", "پاؤں کی انگلی"),
    ("finger", "Finger", "انگلی"),
    ("thumb", "Thumb", "انگوٹھا"),
    ("nail", "Nail", "ناخن"),
    ("claw", "Claw", "پنجہ"),
    ("paw", "Paw", "پنجہ"),
    ("hoof", "Hoof", "کھر"),
    ("horn", "Horn", "سینگ"),
    ("tail", "Tail", "دم"),
    ("wing", "Wing", "پر"),
    ("fin", "Fin", "فن"),
    ("scale", "Scale", "پیمانہ / سکیل"),
    ("shell", "Shell", "خول"),
    ("bone", "Bone", "ہڈی"),
    ("skull", "Skull", "کھوپڑی"),
    ("spine", "Spine", "ریڑھ کی ہڈی"),
    ("rib", "Rib", "پسلی"),
    ("joint", "Joint", "جوڑ"),
    ("muscle", "Muscle", "پٹھہ"),
    ("flesh", "Flesh", "گوشت"),
    ("blood", "Blood", "خون"),
    ("vein", "Vein", "رگ"),
    ("nerve", "Nerve", "اعصاب"),
    ("cell", "Cell", "خلیہ"),
    ("tissue", "Tissue", "ٹشو"),
    ("organ", "Organ", "عضو"),
    ("gland", "Gland", "غدود"),
    ("heart", "Heart", "دل"),
    ("lung", "Lung", "پھیپھڑا"),
    ("liver", "Liver", "جگر"),
    ("brain", "Brain", "دماغ"),
    ("mind", "Mind", "ذہن"),
    ("soul", "Soul", "روح"),
    ("spirit", "Spirit", "روح"),
    ("life", "Life", "زندگی"),
    ("death", "Death", "موت"),
    ("birth", "Birth", "پیدائش"),
    ("seed", "Seed", "بیج"),
    ("egg", "Egg", "انڈا"),
    ("nest", "Nest", "گھونسلہ"),
    ("home", "Home", "گھر"),
    ("house", "House", "مکان"),
    ("hut", "Hut", "جھونپڑی"),
    ("tent", "Tent", "خیمہ"),
    ("camp", "Camp", "کیمپ"),
    ("base", "Base", "بنیاد"),
    ("fort", "Fort", "قلعہ"),
    ("castle", "Castle", "محل"),
    ("palace", "Palace", "محل"),
    ("tower", "Tower", "ٹاور"),
    ("wall", "Wall", "دیوار"),
    ("gate", "Gate", "دروازہ"),
    ("door", "Door", "دروازہ"),
    ("window", "Window", "کھڑکی"),
    ("roof", "Roof", "چھت"),
    ("floor", "Floor", "فرش"),
    ("room", "Room", "کمرہ"),
    ("hall", "Hall", "ہال"),
    ("stair", "Stair", "سیڑھی"),
    ("step", "Step", "قدم"),
    ("path", "Path", "راستہ"),
    ("road", "Road", "سڑک"),
    ("way", "Way", "راستہ"),
    ("street", "Street", "سڑک"),
    ("lane", "Lane", "گلی"),
    ("alley", "Alley", "گلی"),
    ("trail", "Trail", "پگڈنڈی"),
    ("track", "Track", "ٹریک"),
    ("route", "Route", "راستہ"),
    ("line", "Line", "لکیر"),
    ("row", "Row", "قطار"),
    ("queue", "Queue", "قطار"),
    ("rank", "Rank", "رینک"),
    ("file", "File", "فائل"),
    ("list", "List", "فہرست"),
    ("table", "Table", "ٹیبل"),
    ("chart", "Chart", "چارٹ"),
    ("graph", "Graph", "گراف"),
    ("map", "Map", "نقشہ"),
    ("plan", "Plan", "منصوبہ"),
    ("plot", "Plot", "پلاٹ"),
    ("scheme", "Scheme", "سکیم"),
    ("design", "Design", "ڈیزائن"),
    ("draft", "Draft", "ڈرافٹ"),
    ("sketch", "Sketch", "خاکہ"),
    ("draw", "Draw", "بنانا"),
    ("paint", "Paint", "پینٹ"),
    ("color", "Color", "رنگ"),
    ("shade", "Shade", "سایہ"),
    ("tint", "Tint", "رنگت"),
    ("hue", "Hue", "رنگ"),
    ("dye", "Dye", "رنگنا"),
    ("stain", "Stain", "داغ"),
    ("mark", "Mark", "نشان"),
    ("sign", "Sign", "علامت"),
    ("symbol", "Symbol", "علامت"),
    ("logo", "Logo", "لوگو"),
    ("icon", "Icon", "آئیکن"),
    ("badge", "Badge", "بیج"),
    ("crest", "Crest", "کلغی"),
    ("seal", "Seal", "مہر"),
    ("stamp", "Stamp", "مہر"),
    ("print", "Print", "پرنٹ"),
    ("type", "Type", "ٹائپ"),
    ("font", "Font", "فانٹ"),
    ("text", "Text", "متن"),
    ("word", "Word", "لفظ"),
    ("name", "Name", "نام"),
    ("term", "Term", "اصطلاح"),
    ("phrase", "Phrase", "جملہ"),
    ("clause", "Clause", "شق"),
    ("line", "Line", "لائن"),
    ("note", "Note", "نوٹ"),
    ("memo", "Memo", "میمو"),
    ("letter", "Letter", "خط"),
    ("mail", "Mail", "میل"),
    ("post", "Post", "پوسٹ"),
    ("card", "Card", "کارڈ"),
    ("book", "Book", "کتاب"),
    ("page", "Page", "صفحہ"),
    ("leaf", "Leaf", "ورق"),
    ("sheet", "Sheet", "شیٹ"),
    ("paper", "Paper", "کاغذ"),
    ("pen", "Pen", "قلم"),
    ("ink", "Ink", "سیاہی"),
    ("desk", "Desk", "ڈیسک"),
    ("chair", "Chair", "کرسی"),
    ("seat", "Seat", "نشست"),
    ("bench", "Bench", "بینچ"),
    ("bed", "Bed", "بستر"),
    ("cot", "Cot", "چارپائی"),
    ("mat", "Mat", "چٹائی"),
    ("rug", "Rug", "قالین"),
    ("carpet", "Carpet", "قالین"),
    ("cloth", "Cloth", "کپڑا"),
    ("fabric", "Fabric", "کپڑا"),
    ("silk", "Silk", "ریشم"),
    ("wool", "Wool", "اون"),
    ("cotton", "Cotton", "کپاس"),
    ("yarn", "Yarn", "دھاگہ"),
    ("thread", "Thread", "دھاگہ"),
    ("string", "String", "ڈوری"),
    ("rope", "Rope", "رسی"),
    ("cord", "Cord", "ڈوری"),
    ("wire", "Wire", "تار"),
    ("cable", "Cable", "کیبل"),
    ("chain", "Chain", "زنجیر"),
    ("link", "Link", "لنک"),
    ("ring", "Ring", "انگوٹھی"),
    ("hoop", "Hoop", "چھلا"),
    ("loop", "Loop", "لوپ"),
    ("coil", "Coil", "کوائل"),
    ("curl", "Curl", "گھنگرالا"),
    ("twist", "Twist", "موڑ"),
    ("turn", "Turn", "موڑ"),
    ("spin", "Spin", "گھومنا"),
    ("roll", "Roll", "گول کرنا"),
    ("wheel", "Wheel", "پہیہ"),
    ("tire", "Tire", "ٹائر"),
    ("gear", "Gear", "گیئر"),
    ("cog", "Cog", "دانت"),
    ("shaft", "Shaft", "شافٹ"),
    ("axle", "Axle", "دھرا"),
    ("rod", "Rod", "راڈ"),
    ("pole", "Pole", "کھمبا"),
    ("post", "Post", "پوسٹ"),
    ("beam", "Beam", "بیم"),
    ("bar", "Bar", "بار"),
    ("tube", "Tube", "ٹیوب"),
    ("pipe", "Pipe", "پائپ"),
    ("hose", "Hose", "ہوز"),
    ("valve", "Valve", "والو"),
    ("pump", "Pump", "پمپ"),
    ("fan", "Fan", "پنکھا"),
    ("vent", "Vent", "وینٹ"),
    ("duct", "Duct", "ڈکٹ"),
    ("hole", "Hole", "سوراخ"),
    ("gap", "Gap", "خلا"),
    ("slot", "Slot", "سلاٹ"),
    ("slit", "Slit", "سوراخ"),
    ("cut", "Cut", "کٹ"),
    ("tear", "Tear", "پھاڑنا"),
    ("rip", "Rip", "پھاڑنا"),
    ("split", "Split", "چیرنا"),
    ("crack", "Crack", "دراڑ"),
    ("break", "Break", "توڑنا"),
    ("smash", "Smash", "توڑنا"),
    ("crash", "Crash", "ٹکرانا"),
    ("hit", "Hit", "مارنا"),
    ("strike", "Strike", "مارنا"),
    ("beat", "Beat", "پیٹنا"),
    ("punch", "Punch", "مکا"),
    ("kick", "Kick", "لات"),
    ("slap", "Slap", "تھپڑ"),
    ("tap", "Tap", "تھپتھپانا"),
    ("pat", "Pat", "تھپتھپانا"),
    ("rub", "Rub", "رگڑنا"),
    ("wipe", "Wipe", "پونچھنا"),
    ("sweep", "Sweep", "جھاڑو"),
    ("brush", "Brush", "برش"),
    ("comb", "Comb", "کنگھی"),
    ("wash", "Wash", "دھونا"),
    ("clean", "Clean", "صاف کرنا"),
    ("clear", "Clear", "صاف"),
    ("pure", "Pure", "خالص"),
    ("fresh", "Fresh", "تازہ"),
    ("new", "New", "نیا"),
    ("raw", "Raw", "خام"),
    ("rare", "Rare", "نایاب"),
    ("fine", "Fine", "عمدہ"),
    ("nice", "Nice", "اچھا"),
    ("good", "Good", "اچھا"),
    ("great", "Great", "عظیم"),
    ("grand", "Grand", "شاندار"),
    ("huge", "Huge", "بہت بڑا"),
    ("vast", "Vast", "وسیع"),
    ("wide", "Wide", "چوڑا"),
    ("broad", "Broad", "وسیع"),
    ("deep", "Deep", "گہرا"),
    ("high", "High", "اونچا"),
    ("tall", "Tall", "لمبا"),
    ("long", "Long", "طویل"),
    ("big", "Big", "بڑا"),
    ("large", "Large", "بڑا"),
    ("small", "Small", "چھوٹا"),
    ("tiny", "Tiny", "ننھا"),
    ("mini", "Mini", "چھوٹا"),
    ("micro", "Micro", "مائیکرو"),
    ("macro", "Macro", "میکرو"),
    ("mega", "Mega", "میگا"),
    ("giga", "Giga", "گیگا"),
    ("tera", "Tera", "ٹیرا"),
    ("kilo", "Kilo", "کلو"),
    ("milli", "Milli", "ملی"),
    ("centi", "Centi", "سنٹی"),
    ("deci", "Deci", "ڈیسی"),
    ("poly", "Poly", "پولی"),
    ("multi", "Multi", "ملٹی"),
    ("omni", "Omni", "اومنی"),
    ("pan", "Pan", "پین"),
    ("uni", "Uni", "یونی"),
    ("mono", "Mono", "مونو"),
    ("solo", "Solo", "سولو"),
    ("lone", "Lone", "اکیلا"),
    ("only", "Only", "صرف"),
    ("just", "Just", "صرف"),
    ("even", "Even", "یہاں تک کہ"),
    ("also", "Also", "بھی"),
    ("too", "Too", "بھی"),
    ("yet", "Yet", "ابھی تک"),
    ("still", "Still", "ابھی تک"),
    ("now", "Now", "اب"),
    ("then", "Then", "پھر"),
    ("here", "Here", "یہاں"),
    ("there", "There", "وہاں"),
    ("near", "Near", "قریب"),
    ("far", "Far", "دور"),
    ("out", "Out", "باہر"),
    ("in", "In", "اندر"),
    ("up", "Up", "اوپر"),
    ("down", "Down", "نیچے"),
    ("over", "Over", "اوپر"),
    ("under", "Under", "نیچے"),
    ("left", "Left", "بائیں"),
    ("right", "Right", "دائیں"),
    ("front", "Front", "سامنے"),
    ("back", "Back", "پیچھے"),
    ("side", "Side", "پہلو"),
    ("edge", "Edge", "کنارہ"),
    ("rim", "Rim", "کنارہ"),
    ("brim", "Brim", "کنارہ"),
    ("lip", "Lip", "ہونٹ"),
    ("mouth", "Mouth", "منہ"),
    ("nose", "Nose", "ناک"),
    ("eye", "Eye", "آنکھ"),
    ("ear", "Ear", "کان"),
    ("face", "Face", "چہرہ"),
    ("head", "Head", "سر"),
    ("neck", "Neck", "گردن"),
    ("arm", "Arm", "بازو"),
    ("hand", "Hand", "ہاتھ"),
    ("leg", "Leg", "ٹانگ"),
    ("foot", "Foot", "پاؤں"),
    ("toe", "Toe", "انگلی"),
    ("body", "Body", "جسم"),
    ("skin", "Skin", "جلد"),
    ("bone", "Bone", "ہڈی"),
    ("flesh", "Flesh", "گوشت"),
    ("blood", "Blood", "خون"),
    ("mind", "Mind", "ذہن"),
    ("soul", "Soul", "روح"),
    ("heart", "Heart", "دل"),
    ("life", "Life", "زندگی"),
    ("live", "Live", "جینا"),
    ("grow", "Grow", "بڑھنا"),
    ("born", "Born", "پیدا ہونا"),
    ("die", "Die", "مرنا"),
    ("dead", "Dead", "مردہ"),
    ("alive", "Alive", "زندہ"),
    ("awake", "Awake", "بیدار"),
    ("sleep", "Sleep", "سونا"),
    ("dream", "Dream", "خواب"),
    ("wake", "Wake", "جاگنا"),
    ("rise", "Rise", "اٹھنا"),
    ("fall", "Fall", "گرنا"),
    ("drop", "Drop", "گرانا"),
    ("slip", "Slip", "پھسلنا"),
    ("slide", "Slide", "پھسلنا"),
    ("glide", "Glide", "پھسلنا"),
    ("soar", "Soar", "اڑان بھرنا"),
    ("fly", "Fly", "اڑنا"),
    ("swim", "Swim", "تیرنا"),
    ("dive", "Dive", "غوطہ لگانا"),
    ("sink", "Sink", "ڈوبنا"),
    ("float", "Float", "تیرنا"),
    ("drift", "Drift", "بہنا"),
    ("sail", "Sail", "سفر کرنا"),
    ("ride", "Ride", "سواری کرنا"),
    ("drive", "Drive", "چلانا"),
    ("steer", "Steer", "رہنمائی کرنا"),
    ("guide", "Guide", "رہنما"),
    ("lead", "Lead", "قیادت کرنا"),
    ("rule", "Rule", "اصول"),
    ("reign", "Reign", "حکومت"),
    ("king", "King", "بادشاہ"),
    ("lord", "Lord", "آقا"),
    ("god", "God", "خدا"),
    ("idol", "Idol", "آئیڈیل"),
    ("hero", "Hero", "ہیرو"),
    ("star", "Star", "ستارہ"),
    ("icon", "Icon", "آئیکن"),
    ("mark", "Mark", "نشان"),
    ("sign", "Sign", "علامت"),
    ("seal", "Seal", "مہر"),
    ("stamp", "Stamp", "مہر"),
    ("brand", "Brand", "برانڈ"),
    ("logo", "Logo", "لوگو"),
    ("type", "Type", "ٹائپ"),
    ("sort", "Sort", "قسم"),
    ("kind", "Kind", "قسم"),
    ("form", "Form", "شکل"),
    ("shape", "Shape", "شکل"),
    ("size", "Size", "سائز"),
    ("mass", "Mass", "کمیت"),
    ("bulk", "Bulk", "تھوک"),
    ("load", "Load", "بوجھ"),
    ("pack", "Pack", "پیک"),
    ("box", "Box", "بکس"),
    ("case", "Case", "کیس"),
    ("bag", "Bag", "بیگ"),
    ("sack", "Sack", "بوری"),
    ("can", "Can", "کین"),
    ("jar", "Jar", "جار"),
    ("pot", "Pot", "برتن"),
    ("pan", "Pan", "پین"),
    ("cup", "Cup", "کپ"),
    ("mug", "Mug", "مگ"),
    ("bowl", "Bowl", "پیالہ"),
    ("dish", "Dish", "ڈش"),
    ("plate", "Plate", "پلیٹ"),
    ("fork", "Fork", "کانٹا"),
    ("spoon", "Spoon", "چمچ"),
    ("knife", "Knife", "چاقو"),
    ("tool", "Tool", "ٹول"),
    ("gear", "Gear", "گیئر"),
    ("kit", "Kit", "کٹ"),
    ("set", "Set", "سیٹ"),
    ("pack", "Pack", "پیک"),
    ("bunch", "Bunch", "گچھا"),
    ("group", "Group", "گروپ"),
    ("team", "Team", "ٹیم"),
    ("crew", "Crew", "عملہ"),
    ("gang", "Gang", "گینگ"),
    ("band", "Band", "بینڈ"),
    ("club", "Club", "کلب"),
    ("class", "Class", "کلاس"),
    ("grade", "Grade", "گریڈ"),
    ("rank", "Rank", "رینک"),
    ("rate", "Rate", "شرح"),
    ("score", "Score", "سکور"),
    ("mark", "Mark", "نشان"),
    ("point", "Point", "نقطہ"),
    ("spot", "Spot", "مقام"),
    ("dot", "Dot", "نقطہ"),
    ("speck", "Speck", "ذرہ"),
    ("bit", "Bit", "بٹ"),
    ("piece", "Piece", "ٹکڑا"),
    ("part", "Part", "حصہ"),
    ("slice", "Slice", "ٹکڑا"),
    ("chunk", "Chunk", "ٹکڑا"),
    ("lump", "Lump", "ڈھیلا"),
    ("mass", "Mass", "کمیت"),
    ("bulk", "Bulk", "تھوک"),
    ("sum", "Sum", "مجموعہ"),
    ("total", "Total", "کل"),
    ("whole", "Whole", "پورا"),
    ("all", "All", "سب"),
    ("full", "Full", "مکمل"),
    ("pure", "Pure", "خالص"),
    ("clean", "Clean", "صاف"),
    ("clear", "Clear", "صاف"),
    ("plain", "Plain", "سادہ"),
    ("bare", "Bare", "ننگا"),
    ("bald", "Bald", "گنجا"),
    ("nude", "Nude", "ننگا"),
    ("void", "Void", "خالی"),
    ("null", "Null", "کالعدم"),
    ("zero", "Zero", "صفر"),
    ("one", "One", "ایک"),
    ("two", "Two", "دو"),
    ("three", "Three", "تین"),
    ("four", "Four", "چار"),
    ("five", "Five", "پانچ"),
    ("six", "Six", "چھ"),
    ("seven", "Seven", "سات"),
    ("eight", "Eight", "آٹھ"),
    ("nine", "Nine", "نو"),
    ("ten", "Ten", "دس"),
]

# Filter down to strictly 3-5 letters
filtered_tech = [t for t in tech_suffixes if 3 <= len(t[0]) <= 5]
# Make unique
seen = set()
unique_tech = []
for t in filtered_tech:
    if t[0] not in seen:
        seen.add(t[0])
        unique_tech.append(t)

def check_domain(domain):
    try:
        result = subprocess.run(['whois', '-h', 'whois.verisign-grs.com', domain], capture_output=True, text=True, timeout=10)
        output = result.stdout.lower()
        if 'no match for' in output or 'not found' in output:
            return True
        return False
    except Exception as e:
        return None

def run_checks():
    available = []

    domains_to_check = [(f"olive{suffix}.com", suffix, eng, urdu) for suffix, eng, urdu in unique_tech]

    with concurrent.futures.ThreadPoolExecutor(max_workers=20) as executor:
        future_to_data = {executor.submit(check_domain, item[0]): item for item in domains_to_check}
        for future in concurrent.futures.as_completed(future_to_data):
            data = future_to_data[future]
            try:
                is_avail = future.result()
                if is_avail is True:
                    available.append(data)
                elif is_avail is None:
                    # Retry
                    time.sleep(1)
                    if check_domain(data[0]) is True:
                        available.append(data)
            except Exception as exc:
                pass

    # Sort by suffix length, then alphabetically
    available.sort(key=lambda x: (len(x[1]), x[1]))

    with open('olive_tech_domains.md', 'w') as f:
        f.write("| Domain | Suffix | English Meaning | Urdu Meaning (اردو معنی) |\n")
        f.write("| --- | --- | --- | --- |\n")
        for domain, suffix, eng, urdu in available:
            f.write(f"| {domain} | {suffix} | {eng} | {urdu} |\n")

if __name__ == "__main__":
    run_checks()
